repos:
 - repo: local
   hooks:
    - id: lint-js
      name: 'lint solidity js'
      entry: /usr/bin/env bash -c "cd solidity && npm run lint:js"
      files: 'solidity\/.*\/\.js$'
      language: script
      description: "Checks JS code according to the package's linter configuration"
    - id: lint-dashboard-js
      name: 'lint dashboard js'
      entry: /usr/bin/env bash -c "cd solidity/dashboard && npm run js:lint"
      files: 'solidity\/dashboard\/.*\/\.js$'
      language: script
      description: "Checks JS code according to the package's linter configuration"
